# Generated by Django 5.0.1 on 2024-02-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Fournisseur', models.CharField(max_length=100)),
                ('Contact_Nom', models.CharField(max_length=100)),
                ('Contact_Telephone', models.CharField(max_length=200)),
                ('Adresse', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('Code_Postal', models.CharField(max_length=100)),
                ('Pays', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Site_Web', models.CharField(max_length=100)),
            ],
        ),
    ]
