# Generated by Django 5.0.1 on 2024-02-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('prix_unitaire', models.FloatField(max_length=200)),
                ('quantite_en_stock', models.CharField(max_length=100)),
                ('date_creation', models.DateField(max_length=100)),
            ],
        ),
    ]
